### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Twaddler01** [QmelZ/launchpad-redirect#1]
Very simple mod that is very useful.  One suggestion is to make it so you can modify the launchpad so it can either change ALL sectors or one or certain selected sectors.  Like you can pick 3 sectors and only have those destinations changed.  Just gives you a little more customization.

**Comment by QmelZ** [comment]
the mod is supposed to be a simple way to redirect all sectors. if you want to change only one sector or 3 sectors you can just go there and change them manually

i will think about it though
